/** Rithmic wire template_id values (field 154467 in each message). */

export const TemplateId = {

  // Discovery (mobile)

  REQUEST_SYSTEM_INFO: 16,

  RESPONSE_SYSTEM_INFO: 17,

  REQUEST_GATEWAY_INFO: 20,

  RESPONSE_GATEWAY_INFO: 21,



  // Shared session

  REQUEST_LOGIN: 10,

  RESPONSE_LOGIN: 11,

  REQUEST_LOGOUT: 12,

  RESPONSE_LOGOUT: 13,

  REQUEST_HEARTBEAT: 18,

  RESPONSE_HEARTBEAT: 19,

  REJECT: 75,

  FORCED_LOGOUT: 77,



  // Reference / market (ticker)

  REQUEST_REFERENCE_DATA: 14,

  RESPONSE_REFERENCE_DATA: 15,

  REQUEST_MARKET_DATA_UPDATE: 100,

  RESPONSE_MARKET_DATA_UPDATE: 101,

  LAST_TRADE: 150,

  BEST_BID_OFFER: 151,

  HIGH_PRICE_LOW_PRICE: 152,

  CLOSE_PRICE: 155,

  ORDER_BOOK: 156,

  MARKET_MODE: 157,



  // History plant

  REQUEST_TIME_BAR_UPDATE: 200,

  RESPONSE_TIME_BAR_UPDATE: 201,

  REQUEST_TIME_BAR_REPLAY: 202,

  RESPONSE_TIME_BAR_REPLAY: 203,

  REQUEST_TICK_BAR_REPLAY: 206,

  RESPONSE_TICK_BAR_REPLAY: 207,

  TIME_BAR: 250,



  // Order plant session bootstrap

  REQUEST_ORDER_SESSION_CONFIG: 3502,

  REQUEST_LOGIN_INFO: 300,

  RESPONSE_LOGIN_INFO: 301,

  REQUEST_ACCOUNT_LIST: 100030,

  REQUEST_ACCOUNT_LIST_ALT: 302,

  RESPONSE_ACCOUNT_LIST: 303,

  REQUEST_ACCOUNT_RMS_INFO: 304,

  RESPONSE_ACCOUNT_RMS_INFO: 100031,

  RESPONSE_ACCOUNT_RMS_INFO_ALT: 305,

  REQUEST_TRADE_ROUTES: 310,

  REQUEST_MOBILE_APP_INFO: 100002,

  REQUEST_SHOW_ORDERS: 320,

  RESPONSE_SHOW_ORDERS: 321,

  REQUEST_SUBSCRIBE_ORDER_UPDATES: 308,

  RESPONSE_SUBSCRIBE_ORDER_UPDATES: 309,



  RESPONSE_ORDER_SESSION_CONFIG: 3503,

  RESPONSE_MOBILE_APP_CONNECT: 100003,

  RESPONSE_TRADE_ROUTE: 311,



  // Orders

  REQUEST_NEW_ORDER: 312,

  RESPONSE_NEW_ORDER: 313,

  REQUEST_SUBSCRIBE_BRACKET_UPDATES: 336,

  RESPONSE_SUBSCRIBE_BRACKET_UPDATES: 337,

  REQUEST_SHOW_BRACKETS: 338,

  RESPONSE_SHOW_BRACKETS: 339,

  REQUEST_SHOW_BRACKET_STOPS: 340,

  RESPONSE_SHOW_BRACKET_STOPS: 341,

  REQUEST_CANCEL_ALL_ORDERS: 346,

  RESPONSE_CANCEL_ALL_ORDERS: 347,

  RITHMIC_ORDER_NOTIFICATION: 351,

  EXCHANGE_ORDER_NOTIFICATION: 352,

  REQUEST_EXIT_POSITION: 3504,

  RESPONSE_EXIT_POSITION: 3505,



  // PnL plant

  REQUEST_PNL_POSITION_UPDATES: 400,

  RESPONSE_PNL_POSITION_UPDATES: 401,

  INSTRUMENT_PNL_POSITION_UPDATE: 450,

  ACCOUNT_PNL_POSITION_UPDATE: 451,

  REQUEST_PNL_POSITION_SNAPSHOT: 100032,

  INSTRUMENT_PNL_POSITION_UPDATE_ALT: 100033,



  // Mobile market subscribe

  REQUEST_SUBSCRIBE_FOR_UNDERLYING: 100000,

  RESPONSE_MARKET_DATA_SUBSCRIBE: 100001,

  REQUEST_MARKET_DATA_CREDENTIALS: 100004,

  RESPONSE_MARKET_DATA_CREDENTIALS: 100005,

};



export const UserType = {

  TRADER: 3,

};

