/**
 * Generate thin protocol/*.js classes for extension template map entries.
 */
import { writeFile, mkdir } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const PROTO_DIR = join(__dirname, "..", "protocol");

/** @type {{ name: string, id: number, extra?: number[], response?: string, requestDefaults?: Record<string, unknown> }[]} */
const PACKETS = [
  { name: "RequestLogout", id: 12 },
  { name: "ResponseLogout", id: 13 },
  { name: "RequestReferenceData", id: 14, response: "ResponseReferenceData" },
  { name: "ResponseReferenceData", id: 15 },
  { name: "Reject", id: 75 },
  { name: "ForcedLogout", id: 77 },
  { name: "RequestMarketDataUpdate", id: 100, response: "ResponseMarketDataUpdate" },
  { name: "ResponseMarketDataUpdate", id: 101 },
  { name: "LastTrade", id: 150 },
  { name: "BestBidOffer", id: 151 },
  { name: "HighPriceLowPrice", id: 152 },
  { name: "ClosePrice", id: 155 },
  { name: "OrderBook", id: 156 },
  { name: "MarketMode", id: 157 },
  { name: "RequestTimeBarUpdate", id: 200, response: "ResponseTimeBarUpdate" },
  { name: "ResponseTimeBarUpdate", id: 201 },
  { name: "RequestTimeBarReplay", id: 202, response: "ResponseTimeBarReplay" },
  { name: "ResponseTimeBarReplay", id: 203 },
  { name: "RequestTickBarUpdate", id: 204, response: "ResponseTickBarUpdate" },
  { name: "ResponseTickBarUpdate", id: 205 },
  { name: "RequestTickBarReplay", id: 206, response: "ResponseTickBarReplay" },
  { name: "ResponseTickBarReplay", id: 207 },
  { name: "TimeBar", id: 250 },
  { name: "TickBar", id: 251 },
  { name: "ResponseAccountList", id: 303 },
  { name: "ResponseSubscribeForOrderUpdates", id: 309 },
  { name: "ResponseShowOrders", id: 321 },
  { name: "RequestSubscribeToBracketUpdates", id: 336, response: "ResponseSubscribeToBracketUpdates" },
  { name: "ResponseSubscribeToBracketUpdates", id: 337 },
  { name: "RequestShowBrackets", id: 338, response: "ResponseShowBrackets" },
  { name: "ResponseShowBrackets", id: 339 },
  { name: "RequestShowBracketStops", id: 340, response: "ResponseShowBracketStops" },
  { name: "ResponseShowBracketStops", id: 341 },
  { name: "RequestNewOrder", id: 312, response: "ResponseNewOrder" },
  { name: "ResponseNewOrder", id: 313 },
  { name: "RequestCancelAllOrders", id: 346, response: "ResponseCancelAllOrders" },
  { name: "ResponseCancelAllOrders", id: 347 },
  { name: "RithmicOrderNotification", id: 351 },
  { name: "ExchangeOrderNotification", id: 352 },
  { name: "RequestExitPosition", id: 3504, response: "ResponseExitPosition" },
  { name: "ResponseExitPosition", id: 3505 },
  { name: "RequestPnLPositionUpdates", id: 400, response: "ResponsePnLPositionUpdates" },
  { name: "ResponsePnLPositionUpdates", id: 401 },
  { name: "InstrumentPnLPositionUpdate", id: 450, extra: [100033] },
  { name: "AccountPnLPositionUpdate", id: 451 },
  { name: "RequestSubscribeForUnderlying", id: 100000, response: "ResponseMarketDataSubscribe" },
  { name: "ResponseMarketDataSubscribe", id: 100001 },
  { name: "RequestMarketDataCredentials", id: 100004, response: "ResponseMarketDataCredentials" },
  { name: "ResponseMarketDataCredentials", id: 100005 },
  { name: "RequestPnLPositionSnapshot", id: 100032 },
];

function fileName(name) {
  return `${name}.js`;
}

function emitClass({ name, id, extra = [], response }) {
  const isRequest = name.startsWith("Request");
  const imports = [`import { Packet } from "./Packet.js";`];
  if (response) {
    imports.push(`import { ${response} } from "./${response}.js";`);
  }

  const tidExpr = String(id);

  let ctorBody = `    this.template_id = ${tidExpr};\n`;
  if (isRequest) {
    ctorBody += `    this.user_msg = data.user_msg ?? [];\n`;
    ctorBody += `    if (data) this.applyObject(data);\n`;
  }

  const extraArg = extra.length ? `, [${extra.join(", ")}]` : "";
  const responseLine = response ? `\n  static Response = ${response};` : "";

  return `${imports.join("\n")}

export class ${name} extends Packet {
  static MESSAGE_NAME = "${name}";
  static TEMPLATE_ID = ${id};${responseLine}

  ${isRequest ? `constructor(data = {}) {\n    super();\n${ctorBody}  }` : `constructor() {\n    super();\n    this.template_id = ${tidExpr};\n  }`}
}

${name}.register(${extra.length ? `[${extra.join(", ")}]` : ""});
`;
}

await mkdir(PROTO_DIR, { recursive: true });

const exports = [];
for (const spec of PACKETS) {
  const path = join(PROTO_DIR, fileName(spec.name));
  await writeFile(path, emitClass(spec), "utf8");
  exports.push(spec.name);
}

// Patch existing classes for duplicate template ids
const indexBody = `// Auto-generated by tools/generate-packets.mjs
${exports.map((n) => `export { ${n} } from "./${n}.js";`).join("\n")}
`;

await writeFile(join(PROTO_DIR, "extension.js"), indexBody, "utf8");
console.log(`Wrote ${exports.length} packet classes + extension.js`);
